<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ClientWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/WeatherFromIP/src/ClientWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/WeatherFromIP/src/ClientWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="ClientWSDLOperationRequest">
        <part name="inputIPaddress" type="xsd:string"/>
    </message>
    <message name="ClientWSDLOperationResponse">
        <part name="outputWeather" type="xsd:string"/>
    </message>
    <portType name="ClientWSDLPortType">
        <operation name="ClientWSDLOperation">
            <input name="input1" message="tns:ClientWSDLOperationRequest"/>
            <output name="output1" message="tns:ClientWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="ClientWSDLBinding" type="tns:ClientWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ClientWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/WeatherFromIP/src/ClientWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/WeatherFromIP/src/ClientWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="ClientWSDLService">
        <port name="ClientWSDLPort" binding="tns:ClientWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/ClientWSDLService/ClientWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="ClientWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="ClientWSDLPortTypeRole" portType="tns:ClientWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
