<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="country.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/country.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/country.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://www.webserviceX.NET">
    <import location="http://www.webservicex.net/country.asmx?wsdl" namespace="http://www.webserviceX.NET"/>
    <plnk:partnerLinkType name="countrySoapLinkType">
        <plnk:role name="countrySoapRole" portType="ns:countrySoap"/>
    </plnk:partnerLinkType>
</definitions>
